version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install

      # JUnit形式でデータ出力先として junit というディレクトリを作成
      - run: mkdir junit

      # 作成した junit ディレクトリに
      # test-results.xml というファイル名で JUnit 形式のテストの結果を出力
      - run:
          command: node_modules/.bin/mocha test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ./junit/test-results.xml
          when: always

      # 出力した結果の場所を示す    
      - store_test_results:
          path: ./junit
      # CircleCI に読み込み    
      - store_artifacts:
          path: ./junits